feat: добавить service и storage для контроллеров UserController и Fi…
lykkeee/java-filmorate pull request #4
Opened 2023-06-26 10:12 UTC by lykkeee

…lmController

feat: добавить реализацию добавления пользователей в друзья и возможности поставить лайк фильму

2023-06-26 15:20 UTC, YazykovMikhail requested changes

2023-06-26 15:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> getFilms();
Такого метода не должно быть. 
В этом смысл интерфейса что его можно пременить к любой структуре, когда будет реализация с БД, ты не сможешь вернуть структуру бд

2023-06-26 15:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> getUsers();
Такого метода не должно быть. 
В этом смысл интерфейса что его можно пременить к любой структуре, когда будет реализация с БД, ты не сможешь вернуть структуру бд

2023-06-26 15:20 UTC, YazykovMikhail commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(filmId)) {
обрати внимание что  вот этот код с проверка повторяется тут и в deleteLike. 
Стоит вынести его в отдельынй метод и вызывать из метода. 
Избавляйся от дублирвоания кода

Касается и User

2023-06-28 09:07 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
поправлено

2023-06-28 09:07 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> +    @ExceptionHandler(ValidationException.class)
поправлено

2023-06-28 09:08 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +
поправлено

2023-06-28 09:31 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/controllers/FilmController.java
> -        log.info("Запрос на добавление нового фильма:{}", film);
поправлено

2023-06-28 09:31 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(film.getId())) {
поправлено

2023-06-28 09:33 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void nameValidator(String name) {
поправлено

2023-06-28 09:33 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        user.nameValidator(user.getName());
поправлено

2023-06-28 09:39 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (!filmStorage.getFilms().containsKey(filmId)) {
поправлено

2023-06-28 09:39 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserStorage.java
> +    Map<Integer, User> getUsers();
поправлено

2023-06-28 09:40 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +    Map<Integer, Film> getFilms();
поправлено

2023-06-28 10:37 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        log.info("Добавление нового фильма:{}", film);
поправлено

2023-06-28 11:35 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private Set<Long> friendsList;
поправлено

2023-06-28 11:35 UTC, lykkeee commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    private Set<Long> likesList;
поправлено

2023-07-02 13:40 UTC, merged